project:
  name: demo
  
server:
  port: 8080
  servlet:
     context-path: /demo
  
logging: # file和path不同时生效
#   file: log/springbootdemo.log
   path: /log
   
spring:
  jmx:
    enabled: false
  profiles:
    active: ${active:dev}
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?nullCatalogMeansCurrent=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    
##mybatis
mybatis:
   mapper-locations: classpath:mapper/*.xml
   configuration:
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true

