server:
   port: 8080
spring:
   resources:
      static-locations: classpath:/templates/,classpath:/static/
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hanxiao?nullCatalogMeansCurrent=true&serverTimezone=UTC
      username: root
      password: root
   jpa:
      show-sql: true # 默认false，在日志里显示执行的sql语句
      database: mysql
      hibernate:
         ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
logging: # file和path不同时生效
   file: log/springbootdemo.log
   #path: /log